### ISSUE TITLE
'PO Box 123' is invalid

### ISSUE THREAD

**Issue by chenfanggm** [EpicVoyage/pobox-regex#1]
'PO Box 123' is invalid, which is one of your positive case.

Do in javascript:
var reg = new RegExp('(?:P(?:ost(?:al)?)?[\.\-\s]*(?:(?:O(?:ffice)?[\.\-\s]*)?B(?:ox|in|\b|\d)|o(?:ffice|\b)(?:[-\s]*\d)|code)|box[-\s\b]*\d)', 'i');
reg.test('PO Box 123')

**Comment by EpicVoyage** [comment]
Thanks for the report. I think the JavaScript and RegEx engines are a little confusing on this point. In Regular Expressions `\b` indicates a word boundary. In JavaScript (as with other C-like languages), `\b` is the ASCII "bell" character. Take a look at the output of this JavaScript code:

    '\b'.charCodeAt(0); // == ASCII 8

To get this code to work as you expect it to, you will have to escape your backslashes even though you use single quotes:

    var reg = new RegExp('(?:P(?:ost(?:al)?)?[\\.\\-\\s]*(?:(?:O(?:ffice)?[\\.\\-\\s]*)?B(?:ox|in|\\b|\\d)|o(?:ffice|\\b)(?:[-\\s]*\\d)|code)|box[-\\s\\b]*\\d)', 'i');
    reg.test('PO Box 123')

There is an alternative syntax in JavaScript that does not require you to escape the RegEx characters:

    var reg = /(?:P(?:ost(?:al)?)?[\.\-\s]*(?:(?:O(?:ffice)?[\.\-\s]*)?B(?:ox|in|\b|\d)|o(?:ffice|\b)(?:[-\s]*\d)|code)|box[-\s\b]*\d)/i
    reg.test('PO Box 123')

Let me know if I can help any further.

**Comment by chenfanggm** [comment]
@EpicVoyage 
Thank you so much for your detailed explanation. I have solved the problem by your response.
Appreciate!
