### ISSUE TITLE
Negate the entire regExp

### ISSUE THREAD

**Issue by i-yassin** [EpicVoyage/pobox-regex#2]
Any ideas on how to negate the entire regExp? AKA make it valid for the invalid list and invalid for the valid list ?

**Comment by EpicVoyage** [comment]
Can you provide an example of the regex in your code? There are a few ways to negate it, but the programming language and use-case determine which is best.

**Comment by i-yassin** [comment]
I have an input field (address input field) and I wish to allow any address that is not a PO address, your RegExp works fine but what I need is quite the opposite.

Note: I'm using JS to do so.

**Comment by EpicVoyage** [comment]
In JS, all you need is something like this (note the ! in front of the regex test call):

    var reg = /(?:P(?:ost(?:al)?)?[\.\-\s]*(?:(?:O(?:ffice)?[\.\-\s]*)?B(?:ox|in|\b|\d)|o(?:ffice|\b)(?:[-\s]*\d)|code)|box[-\s\b]*\d)/i
    !reg.test('PO Box 123')

**Comment by i-yassin** [comment]
I'm using formValidator in which I'm only allowed to send the regExp as a string. So the issue here is, I need to negate the entire regExp as a string.

**Comment by EpicVoyage** [comment]
You could do a "[negative lookahead](https://stackoverflow.com/questions/164414/how-to-inverse-match-with-regex)" but that is a bit ugly.

If this is the jQuery Form Validator, you can use the example in my last comment as a custom validator: http://www.formvalidator.net/#custom-validators

**Comment by i-yassin** [comment]
This actully might work! Thank you for sugessting that. :)

**Comment by EpicVoyage** [comment]
No problem. Good luck!
