### ISSUE TITLE
false positive

### ISSUE THREAD

**Issue by pmhofman** [EpicVoyage/pobox-regex#4]
Example of a false positive:
"out of the box 123"
the part "box 123" matches.

Other remark: you use case insensitive flag '/i' at the end, yet you use different matches for Office and office.

**Comment by EpicVoyage** [comment]
Is "out of the box 123" from a longer text, or is it part of an address you are dealing with?

For the /i, one catches `pob #`, and the other catches `po #`. It could stand to be normalized to all lower-case.

**Comment by EpicVoyage** [comment]
No further details provided. Closing for now.
